"""Removed duration column and added datetime column with default timestamp creation. Also updated schemas NewPracticeSession and SavedPracticeSession

Revision ID: 21f0d4c2e512
Revises: 3c69ea83e3db
Create Date: 2025-12-16 15:39:34.122439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f0d4c2e512'
down_revision: Union[str, Sequence[str], None] = '3c69ea83e3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('practice_session', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('practice_session', 'date')
    # ### end Alembic commands ###
