"""Added event listener to duration column inside of practice_sessions table. Discovered the total time was not being updated with updates.

Revision ID: 24b4efc938e6
Revises: 700f8b6b5f0e
Create Date: 2025-12-22 17:08:45.301756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b4efc938e6'
down_revision: Union[str, Sequence[str], None] = '700f8b6b5f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
