"""Added default parameter to practice_session id. Trying to get it to generate new uuid for every session.

Revision ID: 25478f344db7
Revises: c87707b270e5
Create Date: 2025-12-15 14:08:13.756649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25478f344db7'
down_revision: Union[str, Sequence[str], None] = 'c87707b270e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
