"""Added AsyncAttrs to Declarative base. Trying to fix issues I'm having getting attributes of joined tables.

Revision ID: 4f6da8d94649
Revises: aa69f438f832
Create Date: 2025-12-22 13:30:24.289836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6da8d94649'
down_revision: Union[str, Sequence[str], None] = 'aa69f438f832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
