"""Added event listener to duration column inside of practice_sessions table. Discovered the total time was not being updated with updates.

Revision ID: 52df1d716a82
Revises: 4f6da8d94649
Create Date: 2025-12-22 16:53:10.197730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52df1d716a82'
down_revision: Union[str, Sequence[str], None] = '4f6da8d94649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
