"""Added event listener to duration column inside of practice_sessions table. Discovered the total time was not being updated with updates.

Revision ID: 700f8b6b5f0e
Revises: 79863c8a3c5a
Create Date: 2025-12-22 16:59:38.643884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700f8b6b5f0e'
down_revision: Union[str, Sequence[str], None] = '79863c8a3c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
