"""Added event listener to duration column inside of practice_sessions table. Discovered the total time was not being updated with updates.

Revision ID: 79863c8a3c5a
Revises: 52df1d716a82
Create Date: 2025-12-22 16:55:58.884479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79863c8a3c5a'
down_revision: Union[str, Sequence[str], None] = '52df1d716a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
