"""Added cascade effect on goal and practice_session foreign keys when deleted.

Revision ID: 9fc2bc1bfeaf
Revises: 24b4efc938e6
Create Date: 2025-12-22 18:27:11.476040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc2bc1bfeaf'
down_revision: Union[str, Sequence[str], None] = '24b4efc938e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('goal_user_id_fkey'), 'goal', type_='foreignkey')
    op.create_foreign_key(None, 'goal', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('practice_session_goal_id_fkey'), 'practice_session', type_='foreignkey')
    op.create_foreign_key(None, 'practice_session', 'goal', ['goal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_session', type_='foreignkey')
    op.create_foreign_key(op.f('practice_session_goal_id_fkey'), 'practice_session', 'goal', ['goal_id'], ['id'])
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.create_foreign_key(op.f('goal_user_id_fkey'), 'goal', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
