"""Adding the Mapped[] construct to follow along with docs. Trying to get joins to work properly.

Revision ID: aa69f438f832
Revises: cd2aba6a59fa
Create Date: 2025-12-22 12:54:17.395852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa69f438f832'
down_revision: Union[str, Sequence[str], None] = 'cd2aba6a59fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
