"""Removed default parameter to practice_session id. Trying to get it to generate new uuid for every session.

Revision ID: c87707b270e5
Revises: d5ff06300d4b
Create Date: 2025-12-15 14:04:00.191319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87707b270e5'
down_revision: Union[str, Sequence[str], None] = 'd5ff06300d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
