"""Adding the Mapped[] construct to follow along with docs. Trying to get joins to work properly.

Revision ID: cd2aba6a59fa
Revises: 085b515ed61e
Create Date: 2025-12-22 12:52:28.354104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2aba6a59fa'
down_revision: Union[str, Sequence[str], None] = '085b515ed61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
