"""Removing date column from practice_session.

Revision ID: d5ff06300d4b
Revises: 898f49462495
Create Date: 2025-12-15 13:57:38.886591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5ff06300d4b'
down_revision: Union[str, Sequence[str], None] = '898f49462495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_session', 'goals',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('practice_session', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('practice_session', 'goals',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
