"""Updated practice_session table to have date, start_time, end_time and duration columns. Schemas allow users to input date, start_time and end_times, but duration is calculated inside the api endpoint func.

Revision ID: f471d191cfc2
Revises: 21f0d4c2e512
Create Date: 2025-12-16 17:43:25.214296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f471d191cfc2'
down_revision: Union[str, Sequence[str], None] = '21f0d4c2e512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('practice_session', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('practice_session', sa.Column('duration', sa.Integer(), nullable=True))
    op.alter_column('practice_session', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_session', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('practice_session', 'duration')
    op.drop_column('practice_session', 'end_time')
    op.drop_column('practice_session', 'start_time')
    # ### end Alembic commands ###
